
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
    $('#btn_edit').trigger('click');
    return false;
  });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
    $('#btn_back').trigger('click');
    return false;
  });
   
 }


 jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header new-july-design">

  <div class="row">
    <div class="col-lg-8">
      <ul class="nav nav-pills tabs-account" id="myTab">
          <!-- <li role="presentation" class="dropdown active">
            <a href="<?php echo base_url(); ?>administrator/oms_party" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Setup<span class="caret"></span></a>
            <ul class="dropdown-menu">
             <li><a href="<?php echo base_url(); ?>administrator/oms_day_close_ledger">Day close Ledger</a></li>
             <li><a href="<?php echo base_url(); ?>administrator/oms_fiscal_year">Fiscal Year</a></li>
             <li><a href="<?= base_url('administrator/oms_voucher_type');?>">Voucher Type</a></li>
              <li><a href="<?= base_url('administrator/oms_ledger_group');?>">Group Creation</a></li>
<li><a href="<?= base_url('administrator/oms_ledger');?>">Ledger Creation</a></li>
             <li><a href="<?= base_url('administrator/oms_opening_ledger');?>">Opening Ledger</a></li>
           </ul>
         </li> -->
         <li><a href="<?= base_url('administrator/user');?>">User</a></li>
         <li class="active"><a href="<?= base_url('administrator/oms_module');?>">Module</a></li>
         <li><a href="<?= base_url('administrator/role');?>">Role</a></li>
       </ul>
     </div>
     
   </div>

 </section>
 <!-- Main content -->
 <div class="tab-content new-july-design">
  <div class="tab-pane fade in active">
    <div class="col-lg-12">
      <section class="content">
       <div class="row" >
         
        <div class="col-md-12 p-0">
         <div class="box box-warning">
          <div class="box-body ">

           <!-- Widget: user widget style 1 -->
           <div class="box box-widget widget-user-2">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header ">
              
             <div class="widget-user-image">
              <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
            </div>
            <!-- /.widget-user-image -->
            <h3 class="widget-user-username">Module</h3>
            <h5 class="widget-user-desc">Detail Module</h5>
            <hr>
          </div>

          
          <div class="form-horizontal" name="form_oms_module" id="form_oms_module" >
            
            <div class="form-wrap ">
              <label for="content" class="label-part">Name: <span><?= _ent($oms_module->name); ?></span></label>
            </div>
            
            <br>
            <br>

            <div class="view-nav">
              <?php is_allowed('oms_module_update', function() use ($oms_module){?>
               <!--  <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="_module (Ctrl+e)" href="<?= site_url('administrator/oms_module/edit/'.$oms_module->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Oms Module']); ?> </a> -->
             <?php }) ?>
             <a class="btn btn-flat btn-default btn_action btn-primary text-white" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/oms_module/'); ?>"> <?= cclang('go_list', ['Module']); ?></a>
           </div>
           
         </div>
       </div>
     </div>
     <!--/box body -->
   </div>
   <!--/box -->

 </div>
</div>
</section>
</div>
<div class="clearfix"></div>
</div>
</div>
<!-- /.content -->
