<style type="text/css">
  .col-md-3.col-sm-4 {
    padding: 10px;
  }
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
  //This page is a result of an autogenerated content made by running test.html with firefox.
  function domo() {

    // Binding keys
    $('*').bind('keydown', 'Ctrl+s', function assets() {
      $('#btn_save').trigger('click');
      return false;
    });

    $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_cancel').trigger('click');
      return false;
    });

    $('*').bind('keydown', 'Ctrl+d', function assets() {
      $('.btn_save_back').trigger('click');
      return false;
    });

  }

  jQuery(document).ready(domo);
</script>
<?php $this->load->view('core_template/fine_upload'); ?>
<!-- Content Header (Page header) -->
<section class="content-header new-july-design">
  <div class="row">
    <div class="col-md-12 h-31">
      <div class="top-bar-wrap">
        <div class="breadcrumb-part-wrap">
          <h4 class="breadcrumb-new">
            <a href="#" data-original-title="" title="">Home</a> <a href="<?= site_url('administrator/menu'); ?>">
              <?= cclang('menu') ?></a> <span class="active-page"><?= cclang('update_button') ?></span>
          </h4>
        </div>
      </div>
    </div>
  </div>

  <!-- <h1>
      <?= cclang('menu') ?>
      <small><?= cclang('update_button', cclang('menu')) ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> <?= cclang('home') ?></a></li>
      <li class=""><a  href="<?= site_url('administrator/menu'); ?>"> <?= cclang('menu') ?></a></li>
      <li class="active"> <?= cclang('update_button') ?></li>
    </ol> -->
</section>
<!-- Main content -->
<div class="tab-content new-july-design">
  <div class="tab-pane fade in active">
    <div class="col-lg-12">
      <section class="content ">
        <div class="row mt-1">
          <div class="col-md-12 mt-1">
            <div class="box box-warning">
              <div class="box-body ">
                <!-- Widget: user widget style 1 -->
                <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    <div class="widget-user-image">
                      <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                    </div>
                    <!-- /.widget-user-image -->
                    <h3 class="widget-user-username"> <?= cclang('menu') ?></h3>
                    <h5 class="widget-user-desc"> <?= cclang('new', cclang('menu')) ?></h5>
                    <hr>
                  </div>

                  <?= form_open('administrator/oms_module/edit_save/' . $this->uri->segment(4), [
                    'name'    => 'form_model_menu',
                    'class'   => 'form-horizontal',
                    'id'      => 'form_model_menu',
                    'method'  => 'POST'
                  ]); ?>
                  <input type="hidden" value="<?= $menu->menu_type_id; ?>" name="menu_type_id">
                  <div class="form-group menu-only">
                    <label for="content" class="col-sm-2 label-part control-label">
                      <?= cclang('icon') ?> </label>
                    <div class="col-sm-8">
                      <input type="hidden" name="icon" id="icon" value="<?= $menu->icon; ?>">
                      <div class="icon-preview <?= $menu->icon_color; ?>">
                        <span class="icon-preview-item"><i class="fa <?= $menu->icon; ?> fa-lg"></i></span>
                      </div>
                      <a class="btn btn-default btn-select-icon btn-flat btn-primary text-white">
                        <?= cclang('select_icon') ?></a>
                      <!-- <div class="form-wrap"> -->


                      <!-- <div class="input-field-part"> -->


                      <!-- <div class="icon-select-wrap"> -->

                      <!-- <div class="icon-preview-part">
                                                        </div>

                                                        <div class="icon-button-part">
                                                        </div> -->
                      <!-- <div class="icon-style-part"> -->
                      <select class="chosen  chosen-select-deselect" name="icon_color" id="icon_color" tabi-ndex="5" data-placeholder="Select Color">
                        <option value="default">Default</option>
                        <?php foreach ($color_icon as $color) : ?>
                          <option value="<?= $color; ?>" <?= $menu->icon_color == $color ? 'selected' : ''; ?>>
                            <?= ucwords(str_replace('-', ' ', $color)); ?>
                          </option>
                        <?php endforeach; ?>
                      </select>
                      <!-- </div> -->
                      <!-- </div> -->
                      <!-- </div> -->
                      <!-- </div> -->


                    </div>
                  </div>

                  <div class="form-group">
                    <label for="content" class="col-sm-2 control-label label-part">
                      <?= cclang('parent') ?></label>

                    <div class="col-sm-8 ">


                      <select class="form-control chosen  chosen-select-deselect" name="parent" id="parent" tabi-ndex="5" data-placeholder="Select Parent">
                        <option value=""></option>

                        <?php foreach (get_menu($menu->menu_type_id) as $row) : ?>
                          <option <?= $row->id == $menu->parent ? 'selected="selected"' : ''; ?> value="<?= $row->id; ?>"><?= ucwords($row->name); ?>
                          </option>
                          <?php if (isset($row->children) and count($row->children)) : ?>
                            <?php create_childern($row->children, $menu->parent, 1); ?>
                          <?php endif ?>
                        <?php endforeach; ?>
                      </select>
                      <small class="info help-block">
                        Select one or more groups.
                      </small>

                    </div>
                  </div>
                  <div class="form-group">
                    <label for="label" class="col-sm-2 control-label label-part">
                      <?= cclang('label') ?> <i class="required">*</i></label>
                    <div class="col-sm-8 ">
                      <div class="input-field-part">
                        <input type="text" class="form-control" name="name" id="label" placeholder="Label" value="<?= set_value('label', $menu->name); ?>">

                      </div>
                      <small class="info help-block">The label of menu.</small>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="link" class=" col-sm-2 control-label label-part">
                      <?= cclang('link') ?> <i class="required">*</i></label>

                    <div class="input-field-part col-sm-8">
                      <input type="text" class="form-control" name="link" id="link" placeholder="Link" value="<?= set_value('link', $menu->link); ?>">

                      <small class="info help-block">The link of menu <i>Example :
                          administrator/blog</i>. short code
                        <code>{{admin_url}}</code></small>
                    </div>

                  </div>

                  <div class="form-group">
                    <label for="content" class="col-sm-2 control-label label-part">
                      <?= cclang('menu_type') ?></label>
                    <div class="col-sm-8 ">

                      <div class="input-field-part">
                        <label class="col-md-6 padding-left-0">
                          <input <?= $menu->type == 'menu' ? 'checked' : ''; ?> type="radio" name="type" class="flat-green menu_type" value="menu">
                          <?= cclang('menu'); ?>
                        </label>
                        <label>
                          <input <?= $menu->type == 'label' ? 'checked' : ''; ?> type="radio" name="type" class="flat-green menu_type" value="label">
                          <?= cclang('label'); ?>
                        </label>

                      </div>
                      <small class="info help-block">
                        Type Of Menu.
                      </small>
                    </div>
                  </div>

                
                  <div class="form-group">
                    <label for="content" class="col-sm-2 control-label label-part">Role</label>
                    <div class="col-sm-8 ">
                      <div class="input-field-part">
                        <div class="row">
                          <div class="col-sm-2 ">
                            <label for="content" class="control-label label-part">Add</label>
                            <input type="checkbox" <?php if ($menu->add == 1) {echo "checked ";} ?> name="add" value="1">
                          </div>
                          <div class="col-sm-2 ">
                            <label for="content" class=" control-label label-part">List</label>
                            <input type="checkbox" <?php if ($menu->list == 1) {echo "checked ";} ?> name="list" value="1">
                          </div>
                          <div class="col-sm-2 ">
                            <label for="content" class=" control-label label-part">View</label>
                            <input type="checkbox" <?php if ($menu->view == 1) {echo "checked ";} ?> name="view" value="1">
                          </div>
                          <div class="col-sm-2 ">
                            <label for="content" class=" control-label label-part">Edit</label>
                            <input type="checkbox" <?php if ($menu->edit == 1) {echo "checked ";} ?> name="edit" value="1">
                          </div>
                          <div class="col-sm-2 ">
                            <label for="content" class=" control-label label-part">Delete</label>
                            <input type="checkbox" <?php if ($menu->delete == 1) {echo "checked ";} ?> name="delete" value="1">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="content" class="col-sm-2 control-label label-part">
                     Self Only</label>
                    <div class="col-sm-8 ">
                      <div class="input-field-part">
                        <input type="checkbox" <?php if ($menu->self_only == 1) { echo "checked ";} ?> name="self_only" value="1">
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="content" class="col-sm-2 control-label label-part">
                      Mobile Menu</label>
                    <div class="col-sm-8 ">
                      <div class="input-field-part">
                        <input type="checkbox" <?php if ($menu->mobile == 1) { echo "checked ";} ?> name="mobile" value="1">
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
            <div class="message">
            </div>
            <div class="row-fluid col-md-7">
              <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save" data-stype='stay' title="save (Ctrl+s)">
                <?= cclang('save_button'); ?></button>
              <a class="btn btn-flat btn-info btn_save btn_action btn_save_back" id="btn_save" data-stype='back' title="save and back to the list (Ctrl+d)">
                <?= cclang('save_and_list'); ?> </a>
              <a class="btn btn-flat btn-default btn_action" id="btn_cancel" title="cancel (Ctrl+x)">
                <?= cclang('cancel'); ?></a>
              <span class="loading loading-hide"><img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> <i>Loading,
                  Saving
                  data</i></span>
            </div>
            <?= form_close(); ?>
          </div>
        </div>
        <!--/box body -->
    </div>
    <!--/box -->
  </div>
</div>
</section>

</div>
</div>
</div>
<!-- /.content -->
<script src="<?= BASE_ASSET; ?>ckeditor/ckeditor.js"></script>
<!-- Page script -->


<div class="modal fade " tabindex="-1" role="dialog" id="modalIcon">
  <div class="modal-dialog full-width" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <?php $this->load->view('backend/standart/administrator/oms_module/partial_icon'); ?>

      </div>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
  $(document).ready(function() {


    /*icon*/


    $('.btn-select-icon').click(function(event) {
      event.preventDefault();

      $('#modalIcon').modal('show');
    });

    $('.icon-container').click(function(event) {
      $('#modalIcon').modal('hide');
      var icon = $(this).find('.icon-class').html();

      icon = $.trim(icon);

      $('#icon').val(icon);

      $('.icon-preview-item .fa').attr('class', 'fa fa-lg ' + icon);
    });

    $('#icon_color').change(function(event) {
      $('.icon-preview-item').attr('class', 'icon-preview-item ' + $(this).val());
    });

    $('#find-icon').keyup(function(event) {
      $('.icon-container').hide();
      var search = $(this).val();

      $('.icon-class').each(function(index, el) {
        var str = $(this).html();
        var patt = new RegExp(search);
        var res = patt.test(str);

        if (res) {
          $(this).parent('.icon-container').show();
        }
      });
    });

    $('.category-icon').each(function(index) {
      $('#category-icon-filter').append('<option value="' + $(this).attr('id') + '">' + $(this).attr(
        'id') + '</option>');
    });

    $('#category-icon-filter').change(function(event) {
      var type = $('#category-icon-filter').val();
      $('.category-icon').hide();
      $('.category-icon#' + type).show();

      if (type == 'all') {
        $('.category-icon').show();
      }
    });

    /*end*/

    $('input[type="radio"].flat-green').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });
    var menu_type = $('.menu_type');

    updateMenuType($('.menu_type[checked]').val());

    menu_type.on('ifClicked', function(event) {
      var type = $(this).val();
      updateMenuType(type);
    });

    function updateMenuType(type) {
      if (type == 'menu') {
        $('.menu-only').show();
      } else {
        $('.menu-only').hide();
      }
    }

    $('#btn_cancel').click(function() {
      swal({
          title: "Are you sure?",
          text: "the data that you have created will be in the exhaust!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes!",
          cancelButtonText: "No!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {
            window.location.href = BASE_URL + 'administrator/menu';
          }
        });

      return false;
    }); /*end btn cancel*/

    $('.btn_save').click(function() {
      $('.message').fadeOut();

      var form_menu = $('#form_model_menu');
      var data_post = form_menu.serialize();
      var save_type = $(this).attr('data-stype');

      $('.loading').show();

      $.ajax({
          url: form_menu.attr('action'),
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          if (res.success) {
            if (save_type == 'back') {
              window.location.href = BASE_URL +
                'administrator/oms_module?act=save&res=success&id=' + res.id;
              return;
            }

            $('.message').printMessage({
              message: res.message
            });
            $('.message').fadeIn().delay(1000).fadeOut();

          } else {
            $('.message').printMessage({
              message: res.message,
              type: 'warning'
            });
            $('.message').fadeIn().delay(1000).fadeOut();
          }

        })
        .fail(function() {
          $('.message').printMessage({
            message: 'Error save data',
            type: 'warning'
          });
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({
            scrollTop: $(document).height()
          }, 1000);
        });

      return false;
    }); /*end btn save*/

  }); /*end doc ready*/
</script>