<style type="text/css">
  #search {
    margin-left: 20px;
    border:none;
    border-bottom: 1px solid #CECECE;
    padding: 5px;
  }
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){

   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
     window.location.href = BASE_URL + '/administrator/permission/add';
     return false;
   });

   $('*').bind('keydown', 'Ctrl+s', function assets() {
     $('#btn_save').trigger('click');
     return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
    if ($('#btn_undo').is(":visible")) {
      $('#btn_undo').trigger('click');
    }
    return false;
  });
 }

 jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header new-july-design" id="new-feb-design">
 <div class="row">


 </div>
  </section>
  <!-- Main content -->

  <div class="tab-content new-july-design">
    <div class="tab-pane fade in active">
      <div class="col-lg-12 mt-24p">
        <section class="content">
         <div class="row"  id="new-feb-body-design">
    
          <div class="col-md-12"  id="box-container">
           <div class="box box-warning">
            <div class="box-body ">
             <!-- Widget: user widget style 1 -->
             <div class="box box-widget widget-user-2">
              <!-- Add the bg color to the header using any of the bg-* classes -->
               
              <div class="widget-user-header ">
              <?php if (check_role_exist_or_not(2, array("add"))) {?> 
               <div class="row pull-right">
      <a class="btn btn-flat pull-right btn-success btn_add_new"   data-stype="back" title="" data-original-title="<?= cclang('create');?>" href="<?= site_url('administrator/role/add'); ?>"><i class="fa fa-plus-square-o"></i> <?= cclang('add_new_button', cclang('permission')); ?></a> 
      </div>
      <?php } ?> 
             
              
            </div>
          </div>

          <div class="table-responsive"> 
            <table  class="table table-bordered table-striped dataTable">
             <thead>
              <tr class="">
                <th><?=cclang('s.n.')?></th>
                <th><?=cclang('Department').' '.cclang('name')?></th>
                <th><?=cclang('action')?></th>
              </tr>
            </thead>
            <tbody id="tbody_oms_documents">
              <?php 
              $sn =0;
              foreach($roles as $role){
                $department = $this->model_role->get_department_name($role->group_id);
                $sn++;?>
                <tr>
                  <td><?php echo $sn;?></td>
                  <td><?php echo @$department->name;?></td>
                  <td>
                    <?php if (check_role_exist_or_not(5, array("edit"))) {?>
                      <a href="<?= site_url('administrator/role/edit/' . $role->group_id); ?>" title='<?= cclang('update'); ?>' class="label-default"><i class="fa fa-edit "></i> </a>
                    <?php }?>
                  </td>
                </tr>
              <?php }?>
            </tbody>
          </table>
        </div>

        <!-- nav-tabs-custom -->
        <div class="message">

        </div>

      </div>
      <!-- /.col -->
    </div>
  </div>
  <!--/box body -->
</div>
<!--/box -->

</div>
</div>
</section>
</div>
<div class="clearfix"></div>
</div>
</div>
<!-- /.content -->


